"""remove password field

Revision ID: 054b01f0a41c
Revises: b9a78a878132
Create Date: 2021-10-23 22:25:08.520449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '054b01f0a41c'
down_revision = 'b9a78a878132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='user')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=64), nullable=False))
    op.create_index('password', 'user', ['password'], unique=False)
    # ### end Alembic commands ###
