"""add password field

Revision ID: 6b4ae7983a44
Revises: 054b01f0a41c
Create Date: 2021-10-23 22:26:24.323787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4ae7983a44'
down_revision = '054b01f0a41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=110), nullable=False))
    op.create_unique_constraint(None, 'user', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
